import type { NextPage } from 'next'
import Head from 'next/head'
import Doors from "../components/Doors";
import Particle from "../components/Particles";

const Home: NextPage = () => {


    return (
    <div >
      <Head>
        <title>Web3Adventtüre</title>
        <meta name="description" content="Generated by Julius and Maxim" />

      </Head>


        <div className = "flex flex-wrap bg-[url('../img/calendar_backdrop.jpg')] h-screen w-screen">

        <Doors className = "h-"/>
        </div>
        <Particle/>


    </div>
  )
}

export default Home
